name: Build and Deploy

on:
    pull_request:
        branches: development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build # build job 이 성공적으로 끝나야만 실행됩니다.

    steps:
      - name: Copy Files to Destination
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          source: ./
          target: /home/ubuntu/srv/ubuntu
          rm: true
    
      - name: delete useless images and containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo cp ${{ secrets.ENV_ROUTE }} ${{ secrets.ENV_DIR_ROUTE }}
            sudo yes y | sudo docker image prune
            sudo yes y | sudo docker container prune
            sudo yes y | sudo docker system prune -af

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          timeout: 180s
          script: |
            sh /home/ubuntu/srv/ubuntu/deploy.sh

# name: Deploy to EC2
# on:
#   pull_request:
#     branches: development

# jobs:
#   build:
#     name: Deploy
#     runs-on: ubuntu-latest
#     env:
#       DEV: ${{ secrets.ENV_VARS }}

#     steps:
#     - name: checkout
#       uses: actions/checkout@main

#     - name: Install Dependencies
#       run: npm install --legacy-peer-deps

#     - name: Build Application
#       run: npm run build
    
#     - name: create remote directory
#       uses: actions/checkout@main
#       with:
#         host: ${{ secrets.HOST }}
#         username: ubuntu
#         password: ${{ secrets.PASSWORD }}
#         script: |
#           whoami
#           mkdir -p /home/ubuntu/srv/ubuntu

#     - name: Deploy to Server
#       uses: appleboy/scp-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ubuntu
#         password: ${{ secrets.PASSWORD }}
#         source: ./
#         target: /home/ubuntu/srv/ubuntu

#     - name: delete useless images and containers
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ubuntu
#         key: ${{ secrets.KEY }}
#         script: |
#           sudo cp ${{ secrets.ENV_ROUTE }} ${{ secrets.ENV_DIR_ROUTE }}
#           sudo yes y | sudo docker image prune
#           sudo yes y | sudo docker container prune
#           sudo yes y | sudo docker system prune -af

#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ubuntu
#         key: ${{ secrets.KEY }}
#         timeout: 180s
#         script: |
#           sh /home/ubuntu/srv/ubuntu/deploy.sh
