name: Build and Deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Application
        run: npm run build
      
      - name: Copy Files to Destination
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          source: ./
          target: /home/ubuntu/srv/ubuntu
          rm: true
    

  deploy:
    runs-on: ubuntu-latest
    needs: build # build job 이 성공적으로 끝나야만 실행됩니다.

    steps:
      - name: delete useless images and containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo cp ${{ secrets.ENV_ROUTE }} ${{ secrets.ENV_DIR_ROUTE }}
            sudo yes y | sudo docker image prune
            sudo yes y | sudo docker container prune
            sudo yes y | sudo docker system prune -af

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          timeout: 3600s
          script: |
            sh /home/ubuntu/srv/ubuntu/deploy.sh
