name: Deploy to EC2

on:
  pull_request:
    branches: development

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: create env file
        run: |
          touch .env
          echo "${{ secret.ENV_VARS }}" >> .env

      - name: create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secret.HOST }}
          username: ubuntu
          password: ${{ secret.PASSWORD }}
          script: whoami
